"""
Django settings for sentinelnexus project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde el archivo .env
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-development')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'submodulos',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',  # Para almacenar resultados de tareas
    'django_celery_beat',     # Para programación de tareas periódicas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sentinelnexus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sentinelnexus.context_processors.grafana_settings',  # Añade esta línea
            ],
        },
    },
]

WSGI_APPLICATION = 'sentinelnexus.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'OPTIONS': {
            'client_encoding': 'UTF8',
            'options': '-c search_path=public',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-mx'  # Español de México

TIME_ZONE = 'America/Mexico_City'  # Zona horaria de México

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout settings
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# Email settings (para desarrollo)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Configuración de Celery apuntando a VM Rocky Linux
REDIS_HOST = os.environ.get('REDIS_HOST', '10.100.100.201')  # Reemplaza con la IP real de tu VM
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'django-db')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/Mexico_City'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutos como límite para tareas
CELERY_RESULT_EXTENDED = True  # Almacenar más detalles en los resultados

# Configuración de Redis para cache
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.environ.get('REDIS_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Configuración de sesiones con Redis
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_CACHE_ALIAS = 'default'

# Configuración de múltiples nodos Proxmox


# Función para obtener nodos activos (que tienen configuración completa)


# Verificación de que al menos un nodo esté configurado


# Mantener compatibilidad con la configuración anterior (nodo principal)


# Configuración de tareas periódicas actualizadas para múltiples nodos
# === CONFIGURACION PROXMOX ===
PROXMOX_HOST = os.environ.get('PROXMOX_HOST', '10.100.100.40')
PROXMOX_USER = os.environ.get('PROXMOX_USER', 'root@pam')
PROXMOX_PASSWORD = os.environ.get('PROXMOX_PASSWORD', '')
PROXMOX_VERIFY_SSL = os.environ.get('PROXMOX_VERIFY_SSL', 'False').lower() == 'true'

PROXMOX = {
    'host': PROXMOX_HOST,
    'user': PROXMOX_USER,
    'password': PROXMOX_PASSWORD,
    'verify_ssl': PROXMOX_VERIFY_SSL
}

# Configuración de múltiples nodos (Compatibilidad con proxmox_manager)
PROXMOX_NODES = {}

# Nodo 1 (Principal)
p1_host = os.environ.get('PROXMOX_NODE1_HOST') or os.environ.get('PROXMOX_HOST')
if p1_host:
    PROXMOX_NODES['node1'] = {
        'host': p1_host,
        'user': os.environ.get('PROXMOX_NODE1_USER') or os.environ.get('PROXMOX_USER'),
        'password': os.environ.get('PROXMOX_NODE1_PASSWORD') or os.environ.get('PROXMOX_PASSWORD'),
        'verify_ssl': False,
        'name': os.environ.get('PROXMOX_NODE1_NAME', 'Node1')
    }

# Nodo 2
if os.environ.get('PROXMOX_NODE2_HOST'):
    PROXMOX_NODES['node2'] = {
        'host': os.environ.get('PROXMOX_NODE2_HOST'),
        'user': os.environ.get('PROXMOX_NODE2_USER'),
        'password': os.environ.get('PROXMOX_NODE2_PASSWORD'),
        'verify_ssl': False,
        'name': os.environ.get('PROXMOX_NODE2_NAME', 'Node2')
    }

# Nodo 3
if os.environ.get('PROXMOX_NODE3_HOST'):
    PROXMOX_NODES['node3'] = {
        'host': os.environ.get('PROXMOX_NODE3_HOST'),
        'user': os.environ.get('PROXMOX_NODE3_USER'),
        'password': os.environ.get('PROXMOX_NODE3_PASSWORD'),
        'verify_ssl': False,
        'name': os.environ.get('PROXMOX_NODE3_NAME', 'Node3')
    }

# Configuración de tareas periódicas
CELERY_BEAT_SCHEDULE = {
    # Monitoreo de nodos Proxmox (CPU, RAM, Disco del HOST) - Cada 1 minuto
    'monitor-proxmox-every-minute': {
        'task': 'submodulos.tasks.monitor_all_proxmox_servers',
        'schedule': crontab(minute='*'),
    },
    # Sincronización de inventario de VMs - Cada 5 minutos (Opcional, si se desea)
    # 'sync-proxmox-inventory': {
    #    'task': 'submodulos.tasks.sync_infrastructure',
    #    'schedule': crontab(minute='*/5'),
    # },
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Directorios adicionales de archivos estáticos
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'sentinelnexus/static'),
    os.path.join(BASE_DIR, 'submodulos/static'),
]

# Configuracion de jazzmin
JAZZMIN_SETTINGS = {
    # Títulos
    "site_title": "SentinelNexus Admin",
    "site_header": "SentinelNexus",
    "site_brand": "SentinelNexus",

    # Logo
    "site_logo": None, 

    # Texto de bienvenida
    "welcome_sign": "Bienvenido al Admin de SentinelNexus",

    # Copyright
    "copyright": "SentinelNexus",

    # === EL TEMA OSCURO ===
    "theme": "darkly",
    "dark_mode_theme": "darkly",

    # === COLORES PERSONALIZADOS ===
    # (Tomados de la captura de tu dashboard)
    "custom_colors": {
        "primary": "#3498DB",       # El azul brillante de las tarjetas (links, botones)
        "secondary": "#2A3F54",     # Gris/azul para botones secundarios
        "success": "#27ae60",       # Verde de "ONLINE"
        "info": "#3498DB",
        "warning": "#f39c12",
        "danger": "#e74c3c",
        "light": "#2A3F54",         # Fondo de los "paneles" (ej: "Submodulos")
        "dark": "#1a2133",          # Fondo principal (el más oscuro de tu dashboard)
    },

    # === AJUSTES DE UI ===
    "show_ui_builder": True, # ¡El engranaje volverá a aparecer!

    "ui_tweaks": {
        "navbar_fixed": True,
        "sidebar_fixed": True,
        "sidebar_dark": True,       # Fuerza el menú lateral a ser oscuro
        "navbar_dark": True,        # Fuerza la barra de navegación a ser oscura
        "theme": "darkly",          # Aplica el tema oscuro
    },

    "custom_css": "admin/custom_admin.css",

    # === MENÚ SUPERIOR ===
    "topmenu_links": [
        {"name": "Ver Dashboard", "url": "/nodes", "new_window": False},
        {"model": "submodulos.ProxmoxServer"},
    ],

    # === ICONOS (AHORA COMPLETO) ===
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "submodulos.ProxmoxServer": "fas fa-server",
        "submodulos.Server": "fas fa-hdd",
        "submodulos.ServerMetric": "fas fa-chart-line",
        "submodulos.ServerMetrics": "fas fa-chart-bar",
        "submodulos.MaquinaVirtual": "fas fa-desktop",
        "submodulos.Nodo": "fas fa-network-wired",
    },
}

# --- CONFIGURACION PROXMOX ---
PROXMOX = {
    'host': '10.100.100.40',     # <--- Pon la IP de tu Proxmox Físico
    'user': 'root@pam',          # <--- Usamos root para ir a la segura
    'password': 'Andres_zabala1983', # <--- ¡Pon la clave real aquí!
    'verify_ssl': False
}