# Generated by Django 5.2 on 2025-11-07 15:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaPeriodo',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
            ],
            options={
                'verbose_name': 'Período de Auditoría',
                'verbose_name_plural': 'Períodos de Auditoría',
                'db_table': 'age_auditoria_periodo',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaPeriodo',
            fields=[
                ('periodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('nivel_agregacion', models.CharField(choices=[('cluster', 'Cluster'), ('datacenter', 'Datacenter'), ('nodo', 'Nodo')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Período de Estadística',
                'verbose_name_plural': 'Períodos de Estadística',
                'db_table': 'age_estadistica_periodo',
            },
        ),
        migrations.CreateModel(
            name='MaquinaVirtual',
            fields=[
                ('vm_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vmid', models.IntegerField()),
                ('vm_type', models.CharField(choices=[('qemu', 'KVM'), ('lxc', 'Contenedor LXC')], default='qemu', max_length=10)),
                ('estado', models.CharField(choices=[('running', 'En ejecución'), ('stopped', 'Detenido'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('is_monitored', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Máquina Virtual',
                'verbose_name_plural': 'Máquinas Virtuales',
                'db_table': 'age_maquina_virtual',
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('nodo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_hardware', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
                ('ultimo_mantenimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proxmox_node_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'db_table': 'age_nodo',
            },
        ),
        migrations.CreateModel(
            name='ProxmoxServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hostname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('node_name', models.CharField(default='pve', max_length=100, verbose_name='Nombre del Nodo (ej: www, prx1)')),
                ('verify_ssl', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_cores', models.IntegerField(default=0)),
                ('cpu_model', models.CharField(blank=True, max_length=255)),
                ('ram_total_bytes', models.BigIntegerField(default=0)),
                ('storage_total_bytes', models.BigIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servidor Proxmox',
                'verbose_name_plural': 'Servidores Proxmox',
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('tipo_recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Recurso',
                'verbose_name_plural': 'Tipos de Recursos',
                'db_table': 'age_tipo_recurso',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRecursosCabecera',
            fields=[
                ('auditoria_cabecera_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='submodulos.auditoriaperiodo')),
                ('maquina_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='submodulos.maquinavirtual')),
            ],
            options={
                'verbose_name': 'Cabecera de Auditoría de Recursos',
                'verbose_name_plural': 'Cabeceras de Auditoría de Recursos',
                'db_table': 'age_auditoria_recursos_cabecera',
            },
        ),
        migrations.CreateModel(
            name='LocalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='submodulos__timesta_256f5c_idx')],
            },
        ),
        migrations.AddField(
            model_name='maquinavirtual',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas_virtuales', to='submodulos.nodo'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='proxmox_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='submodulos.proxmoxserver'),
        ),
        migrations.CreateModel(
            name='MetricsAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_cpu', models.FloatField(default=0.0)),
                ('avg_memory', models.FloatField(default=0.0)),
                ('avg_disk', models.FloatField(default=0.0)),
                ('max_cpu', models.FloatField(default=0.0)),
                ('max_memory', models.FloatField(default=0.0)),
                ('max_disk', models.FloatField(default=0.0)),
                ('total_network_in', models.BigIntegerField(default=0)),
                ('total_network_out', models.BigIntegerField(default=0)),
                ('vm_count', models.IntegerField(default=0)),
                ('active_vm_count', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_aggregations', to='submodulos.proxmoxserver')),
            ],
            options={
                'verbose_name': 'Agregación de Métricas',
                'verbose_name_plural': 'Agregaciones de Métricas',
            },
        ),
        migrations.CreateModel(
            name='RecursoFisico',
            fields=[
                ('recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacidad_disponible', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(models.F('capacidad_total'))])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='submodulos.nodo')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recursos', to='submodulos.tiporecurso')),
            ],
            options={
                'verbose_name': 'Recurso Físico',
                'verbose_name_plural': 'Recursos Físicos',
                'db_table': 'age_recurso_fisico',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaRecursosDetalle',
            fields=[
                ('auditoria_detalle_id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_uso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auditoria_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='submodulos.auditoriarecursoscabecera')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_auditoria', to='submodulos.recursofisico')),
            ],
            options={
                'verbose_name': 'Detalle de Auditoría de Recursos',
                'verbose_name_plural': 'Detalles de Auditoría de Recursos',
                'db_table': 'age_auditoria_recursos_detalle',
            },
        ),
        migrations.CreateModel(
            name='AsignacionRecursosInicial',
            fields=[
                ('asignacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_asignada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('maquina_virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='submodulos.maquinavirtual')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='submodulos.recursofisico')),
            ],
            options={
                'verbose_name': 'Asignación de Recursos Inicial',
                'verbose_name_plural': 'Asignaciones de Recursos Iniciales',
                'db_table': 'age_asignacion_recursos_inicial',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('node', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('proxmox_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_servers', to='submodulos.proxmoxserver')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('uptime', models.BigIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='submodulos.server')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ServerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('disk_total', models.BigIntegerField(default=0)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('uptime', models.BigIntegerField(default=0)),
                ('load_average', models.FloatField(default=0.0)),
                ('status', models.CharField(default='online', max_length=20)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_metrics', to='submodulos.proxmoxserver')),
            ],
            options={
                'verbose_name': 'Métrica de Servidor',
                'verbose_name_plural': 'Métricas de Servidores',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('so_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('arquitectura', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistemas Operativos',
                'db_table': 'age_sistema_operativo',
                'unique_together': {('nombre', 'version', 'arquitectura')},
            },
        ),
        migrations.AddField(
            model_name='maquinavirtual',
            name='sistema_operativo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='submodulos.sistemaoperativo'),
        ),
        migrations.CreateModel(
            name='EstadisticaRecursos',
            fields=[
                ('estadistica_id', models.AutoField(primary_key=True, serialize=False)),
                ('entidad_id', models.IntegerField()),
                ('tipo_entidad', models.CharField(choices=[('cluster', 'Cluster'), ('datacenter', 'Datacenter'), ('nodo', 'Nodo')], max_length=20)),
                ('uso_promedio', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('uso_maximo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('uso_minimo', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_disponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='submodulos.estadisticaperiodo')),
                ('tipo_recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='submodulos.tiporecurso')),
            ],
            options={
                'verbose_name': 'Estadística de Recursos',
                'verbose_name_plural': 'Estadísticas de Recursos',
                'db_table': 'age_estadistica_recursos',
            },
        ),
        migrations.CreateModel(
            name='VMMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('disk_read', models.BigIntegerField(default=0)),
                ('disk_write', models.BigIntegerField(default=0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('uptime', models.BigIntegerField(default=0)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_metrics', to='submodulos.maquinavirtual')),
            ],
            options={
                'verbose_name': 'Métrica de VM',
                'verbose_name_plural': 'Métricas de VMs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['nombre'], name='age_nodo_nombre_501d42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='metricsaggregation',
            unique_together={('server', 'date')},
        ),
        migrations.AddIndex(
            model_name='servermetric',
            index=models.Index(fields=['timestamp'], name='submodulos__timesta_b5b6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetric',
            index=models.Index(fields=['server', 'timestamp'], name='submodulos__server__924594_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['server', '-timestamp'], name='submodulos__server__3e75c6_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['-timestamp'], name='submodulos__timesta_63a7b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='maquinavirtual',
            unique_together={('nodo', 'vmid')},
        ),
        migrations.AddIndex(
            model_name='vmmetrics',
            index=models.Index(fields=['vm', '-timestamp'], name='submodulos__vm_id_c65386_idx'),
        ),
        migrations.AddIndex(
            model_name='vmmetrics',
            index=models.Index(fields=['-timestamp'], name='submodulos__timesta_9e4fbc_idx'),
        ),
    ]
