# Generated by Django 5.2 on 2025-12-18 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servermetric',
            options={'ordering': ['-created_at'], 'verbose_name': 'Métrica de Servidor', 'verbose_name_plural': 'Métricas de Servidores'},
        ),
        migrations.RemoveIndex(
            model_name='servermetric',
            name='submodulos__timesta_b5b6c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='servermetric',
            name='submodulos__server__924594_idx',
        ),
        #migrations.RemoveField(
      #      model_name='server',
       #     name='proxmox_server',
     #   ),
        migrations.RemoveField(
            model_name='servermetric',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='memory_usage',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='server',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='servermetric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servermetric',
            name='node_name',
            field=models.CharField(default='Desconocido', max_length=50, verbose_name='Nombre del Nodo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servermetric',
            name='ram_usage',
            field=models.FloatField(default=0.0, verbose_name='Uso RAM (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='cpu_usage',
            field=models.FloatField(verbose_name='Uso CPU (%)'),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='uptime',
            field=models.IntegerField(verbose_name='Tiempo Encendido (seg)'),
        ),
    ]
