# Generated by Django 5.2 on 2025-05-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='proxmox_node_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='proxmox_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_servers', to='submodulos.proxmoxserver'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['nombre'], name='age_nodo_nombre_501d42_idx'),
        ),
    ]
