# Generated by Django 5.2 on 2025-09-18 21:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0002_nodo_proxmox_node_id_server_proxmox_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('avg_cpu', models.FloatField(default=0.0)),
                ('avg_memory', models.FloatField(default=0.0)),
                ('avg_disk', models.FloatField(default=0.0)),
                ('max_cpu', models.FloatField(default=0.0)),
                ('max_memory', models.FloatField(default=0.0)),
                ('max_disk', models.FloatField(default=0.0)),
                ('total_network_in', models.BigIntegerField(default=0)),
                ('total_network_out', models.BigIntegerField(default=0)),
                ('vm_count', models.IntegerField(default=0)),
                ('active_vm_count', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_aggregations', to='submodulos.proxmoxserver')),
            ],
            options={
                'verbose_name': 'Agregación de Métricas',
                'verbose_name_plural': 'Agregaciones de Métricas',
                'unique_together': {('server', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ServerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('disk_total', models.BigIntegerField(default=0)),
                ('disk_used', models.BigIntegerField(default=0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('uptime', models.BigIntegerField(default=0)),
                ('load_average', models.FloatField(default=0.0)),
                ('status', models.CharField(default='online', max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_metrics', to='submodulos.proxmoxserver')),
            ],
            options={
                'verbose_name': 'Métrica de Servidor',
                'verbose_name_plural': 'Métricas de Servidores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='submodulos__server__3e75c6_idx'), models.Index(fields=['-timestamp'], name='submodulos__timesta_63a7b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='VMMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('cpu_cores', models.IntegerField(default=1)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('memory_total', models.BigIntegerField(default=0)),
                ('memory_used', models.BigIntegerField(default=0)),
                ('disk_read', models.BigIntegerField(default=0)),
                ('disk_write', models.BigIntegerField(default=0)),
                ('network_in', models.BigIntegerField(default=0)),
                ('network_out', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='unknown', max_length=20)),
                ('uptime', models.BigIntegerField(default=0)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vm_metrics', to='submodulos.maquinavirtual')),
            ],
            options={
                'verbose_name': 'Métrica de VM',
                'verbose_name_plural': 'Métricas de VMs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vm', '-timestamp'], name='submodulos__vm_id_c65386_idx'), models.Index(fields=['-timestamp'], name='submodulos__timesta_9e4fbc_idx')],
            },
        ),
    ]
