# Generated by Django 5.2 on 2025-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0002_alter_servermetric_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=100, verbose_name='Nombre de VM')),
                ('server_origin', models.CharField(max_length=50, verbose_name='Servidor Origen')),
                ('cpu_usage', models.FloatField(verbose_name='Uso CPU (%)')),
                ('ram_usage', models.FloatField(verbose_name='Uso RAM (%)')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Métrica de VM',
                'verbose_name_plural': 'Métricas de VMs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='server',
            name='proxmox_server',
        ),
    ]
