# Generated by Django 4.2.27 on 2026-01-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0003_vmmetric_remove_server_proxmox_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha Predicha')),
                ('predicted_cpu_usage', models.FloatField(verbose_name='CPU Predicha (%)')),
                ('predicted_memory_usage', models.FloatField(verbose_name='Memoria Predicha (%)')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Es Anomalía')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='submodulos.maquinavirtual')),
            ],
            options={
                'verbose_name': 'Predicción de VM',
                'verbose_name_plural': 'Predicciones de VMs',
                'db_table': 'age_vm_prediction',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='age_vm_pred_timesta_693f70_idx')],
                'unique_together': {('vm', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='ServerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Fecha Predicha')),
                ('predicted_cpu_usage', models.FloatField(verbose_name='CPU Predicha (%)')),
                ('predicted_memory_usage', models.FloatField(verbose_name='Memoria Predicha (%)')),
                ('confidence_lower', models.FloatField(blank=True, null=True, verbose_name='Confianza Inferior')),
                ('confidence_upper', models.FloatField(blank=True, null=True, verbose_name='Confianza Superior')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='submodulos.proxmoxserver')),
            ],
            options={
                'verbose_name': 'Predicción de Servidor',
                'verbose_name_plural': 'Predicciones de Servidores',
                'db_table': 'age_server_prediction',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='age_server__timesta_7e194c_idx')],
                'unique_together': {('server', 'timestamp')},
            },
        ),
    ]
