# Generated by Django 5.2 on 2026-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0003_vmmetric_remove_server_proxmox_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Alerta'), ('ACTION', 'Acción Táctica'), ('CRITICAL', 'Fallo Crítico')], default='INFO', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Agente',
                'verbose_name_plural': 'Logs de Agentes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
