# Generated by Django 5.2 on 2026-01-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0004_agentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinavirtual',
            name='is_critical',
            field=models.BooleanField(default=False, verbose_name='Es Crítica (Watchdog)'),
        ),
    ]
