# Generated by Django 4.2.27 on 2026-01-21 13:40

from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0005_maquinavirtual_is_critical'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(default='Unknown', max_length=50, verbose_name='Nombre del Nodo')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='Uso CPU (%)')),
                ('ram_usage', models.FloatField(default=0.0, verbose_name='Uso RAM (%)')),
                ('uptime', models.IntegerField(default=0, verbose_name='Tiempo Encendido (seg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Métrica de Servidor (Agente)',
                'verbose_name_plural': 'Métricas de Servidores (Agente)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='servermetric',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='vmmetric',
            options={'ordering': ['-created_at'], 'verbose_name': 'Métrica de VM (Agente)', 'verbose_name_plural': 'Métricas de VMs (Agente)'},
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='node_name',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='ram_usage',
        ),
        migrations.AddField(
            model_name='servermetric',
            name='disk_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='submodulos.server'),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='localmetric',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='localmetric',
            name='disk_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='localmetric',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='uptime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vmmetric',
            name='cpu_usage',
            field=models.FloatField(default=0.0, verbose_name='Uso CPU (%)'),
        ),
        migrations.AlterField(
            model_name='vmmetric',
            name='ram_usage',
            field=models.FloatField(default=0.0, verbose_name='Uso RAM (%)'),
        ),
        migrations.AlterField(
            model_name='vmmetric',
            name='server_origin',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='Servidor Origen'),
        ),
        migrations.AlterField(
            model_name='vmmetric',
            name='status',
            field=models.CharField(default='unknown', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vmmetric',
            name='vm_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Nombre de VM'),
        ),
        migrations.AddIndex(
            model_name='servermetric',
            index=models.Index(fields=['timestamp'], name='submodulos__timesta_b5b6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetric',
            index=models.Index(fields=['server', 'timestamp'], name='submodulos__server__924594_idx'),
        ),
    ]
