# Generated by Django 4.2.27 on 2026-01-22 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0006_vmprediction_serverprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vmmetrics',
            name='vm',
        ),
        migrations.DeleteModel(
            name='ServerMetrics',
        ),
        migrations.DeleteModel(
            name='VMMetrics',
        ),
    ]
