# Generated by Django 4.2.27 on 2026-01-22 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0007_remove_vmmetrics_vm_delete_servermetrics_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servermetric',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Métrica de Servidor', 'verbose_name_plural': 'Métricas de Servidores'},
        ),
        migrations.AlterModelOptions(
            name='vmmetric',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Métrica de VM', 'verbose_name_plural': 'Métricas de VMs'},
        ),
        migrations.RenameField(
            model_name='servermetric',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='vmmetric',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='servermetric',
            name='node_name',
        ),
        migrations.AddField(
            model_name='servermetric',
            name='disk_usage',
            field=models.FloatField(default=0, verbose_name='Uso Disco (%)'),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='submodulos.proxmoxserver'),
        ),
        migrations.AlterField(
            model_name='servermetric',
            name='ram_usage',
            field=models.FloatField(db_column='memory_usage', verbose_name='Uso RAM (%)'),
        ),
    ]
