# Generated by Django 4.2.27 on 2026-05-24 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0008_alter_servermetric_options_alter_vmmetric_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XAIExplanationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(choices=[('server', 'Servidor Proxmox'), ('vm', 'Máquina Virtual')], max_length=20)),
                ('timestamp_prediccion', models.DateTimeField(verbose_name='Fecha Objetivo Predicha')),
                ('cpu_predicha', models.FloatField(verbose_name='CPU Predicha (%)')),
                ('ram_predicha', models.FloatField(verbose_name='RAM Predicha (%)')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='Es Anomalía')),
                ('diagnostico_evento', models.CharField(max_length=255, verbose_name='Diagnóstico de Evento')),
                ('explicacion_texto', models.TextField(verbose_name='Explicación Detallada (Narrativa)')),
                ('accion_recomendada', models.CharField(max_length=255, verbose_name='Acción Recomendada')),
                ('valores_shap', models.JSONField(verbose_name='Valores SHAP Raw')),
                ('features_usadas', models.JSONField(verbose_name='Características de Entrada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xai_logs', to='submodulos.proxmoxserver')),
                ('vm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xai_logs', to='submodulos.maquinavirtual')),
            ],
            options={
                'verbose_name': 'Registro de Explicación XAI',
                'verbose_name_plural': 'Registros de Explicaciones XAI',
                'db_table': 'age_xai_explanation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
