# Generated by Django 4.2.27 on 2026-08-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submodulos', '0009_servermetric_node_name_xaiexplanationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servermetric',
            name='node_name',
            field=models.CharField(default='pve', max_length=100, verbose_name='Nombre del Nodo'),
        ),
    ]
